//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastCakeProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
        [DisplayName("Mã khách hàng")]
        public int customerId { get; set; }
        [DisplayName("Tên đăng nhập")]
        public string username { get; set; }
        [DisplayName("Mật khẩu")]
        public string password { get; set; }
        [DisplayName("Tên")]
        public string customerName { get; set; }
        [DisplayName("Địa chỉ")]
        public string customerAddress { get; set; }
        [DisplayName("Số điện thoại")]
        public int customerPhone { get; set; }
        [DisplayName("Email")]
        public string customerEmail { get; set; }
        [DisplayName("Ngày tạo")]
        public System.DateTime createAt { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
