//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastCakeProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OrderDetail
    {
        [DisplayName("Mã chi tiết đơn hàng")]
        public int oroderDetailId { get; set; }
        [DisplayName("Mã đơn hàng")]
        public int orderId { get; set; }
        [DisplayName("Mã sản phẩm")]
        public int productId { get; set; }
        [DisplayName("Số lượng")]
        public int quantity { get; set; }
        [DisplayName("Giá")]
        public decimal price { get; set; }

        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
