//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastCakeProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        [DisplayName("Mã đơn hàng")]
        public int orderId { get; set; }
        [DisplayName("Mã khách hàng")]
        public int customerId { get; set; }
        [DisplayName("Mã nhân viên")]
        public Nullable<int> employeeId { get; set; }
        [DisplayName("Tổng giá tiền")]
        public decimal totalPrice { get; set; }
        [DisplayName("Trạng thái")]
        public int status { get; set; }
        [DisplayName("Ngày tạo")]
        public System.DateTime createAt { get; set; }
        [DisplayName("Địa chỉ khách hàng")]
        public string customerAddress { get; set; }
        [DisplayName("Tên khách hàng")]
        public string customerName { get; set; }
        [DisplayName("Số điện thoại khách hàng")]
        public int customerPhone { get; set; }

        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
