//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastCakeProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        [DisplayName("Mã sản phẩm")]
        public int productId { get; set; }
        [DisplayName("Tên sản phẩm")]
        public string productName { get; set; }
        [DisplayName("Ảnh")]
        public string productImage { get; set; }
        [DisplayName("Giá")]
        public decimal productPrice { get; set; }
        [DisplayName("Ngày tạo")]
        public System.DateTime createAt { get; set; }
        [DisplayName("Mô tả")]
        public string productDescription { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
